### ISSUE TITLE
still relevant? 

### ISSUE THREAD

**Issue by keighrim** [clamsproject/app-nlp-example#8]
The app-writing guidelines are now written in the app template (`clams develop`) and the https://sdk.clams.ai website is also updated accordingly. 

@marcverhagen do you plan to keep this repo up to date with SDK updates, or do you want to incorporate material here into the SDK documentation?

**Comment by marcverhagen** [comment]
Good question. Probably the latter.

**Comment by keighrim** [comment]
Closed via https://github.com/clamsproject/clams-python/issues/161.
